### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by atkinsonchristian** [vanelk/alexa-pi#1]
Hi, I have Alexa working but your code doesn't seem to work. I receive an error when running npm start

 computer@raspberrypi:/opt/alexa/alexa-pi $ npm start

> GUI@1.0.0 start /opt/alexa/alexa-pi
> node app.js

/opt/alexa/alexa-pi/app.js:34
    throw new Error(`Wake worker error: ${data}`);
    ^

Error: Wake worker error: Error opening audio device (null) for capture: Connection refused

    at Socket.<anonymous> (/opt/alexa/alexa-pi/app.js:34:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GUI@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GUI@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/computer/.npm/_logs/2023-03-12T12_00_26_172Z-debug.log
computer@raspberrypi:/opt/alexa/alexa-pi $ 

Any ideas?
Thanks.

**output of systemctl statu alexapi.service**

opt/alexa/alexa-pi $ sudo systemctl start alexapi
systemctl status alexapi
Job for alexapi.service failed because the control process exited with error code.
See "systemctl status alexapi.service" and "journalctl -xe" for details.
● alexapi.service - Alexa client for raspberry pi
     Loaded: loaded (/lib/systemd/system/alexapi.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-03-12 13:48:50 EET; 26ms ago
    Process: 13334 ExecStartPre=/usr/bin/pulseaudio --start --log-target=syslog --system=false (code=exited, status=217/USER)
        CPU: 13ms

Mar 12 13:48:50 raspberrypi systemd[1]: Starting Alexa client for raspberry pi...
Mar 12 13:48:50 raspberrypi systemd[13334]: alexapi.service: Failed to determine user credentials: No such process
Mar 12 13:48:50 raspberrypi systemd[13334]: alexapi.service: Failed at step USER spawning /usr/bin/pulseaudio: No such process
Mar 12 13:48:50 raspberrypi systemd[1]: alexapi.service: Control process exited, code=exited, status=217/USER
Mar 12 13:48:50 raspberrypi systemd[1]: alexapi.service: Failed with result 'exit-code'.
Mar 12 13:48:50 raspberrypi systemd[1]: Failed to start Alexa client for raspberry pi.
computer@raspberrypi:/opt/alexa/alexa-pi $ 

**output of journalctl -xe**

computer@raspberrypi:/opt/alexa/alexa-pi $ journalctl -xe
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit alexapi.service has entered the 'failed' state with result 'exit-code'.
Mar 12 13:48:50 raspberrypi systemd[1]: Failed to start Alexa client for raspberry pi.
░░ Subject: A start job for unit alexapi.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit alexapi.service has finished with a failure.
░░ 
░░ The job identifier is 2148 and the job result is failed.
Mar 12 13:48:50 raspberrypi sudo[13331]: pam_unix(sudo:session): session closed for user root
Mar 12 13:48:55 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.890000000000 crc 10
Mar 12 13:48:55 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.890000000000.10 is not registered.
Mar 12 13:50:00 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.490000000000 crc da
Mar 12 13:50:00 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.490000000000.da is not registered.
Mar 12 13:51:03 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.c90000000000 crc 56
Mar 12 13:51:03 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.c90000000000.56 is not registered.
Mar 12 13:52:20 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.290000000000 crc bf
Mar 12 13:52:20 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.290000000000.bf is not registered.
Mar 12 13:53:00 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.a90000000000 crc 33
Mar 12 13:53:00 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.a90000000000.33 is not registered.
Mar 12 13:53:49 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.690000000000 crc f9
Mar 12 13:53:49 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.690000000000.f9 is not registered.
Mar 12 13:54:41 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.e90000000000 crc 75
Mar 12 13:54:41 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.e90000000000.75 is not registered.
Mar 12 13:55:20 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.190000000000 crc 01
Mar 12 13:55:20 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.190000000000.01 is not registered.
Mar 12 13:56:24 raspberrypi kernel: w1_master_driver w1_bus_master1: Attaching one wire slave 00.990000000000 crc 8d
Mar 12 13:56:24 raspberrypi kernel: w1_master_driver w1_bus_master1: Family 0 for 00.990000000000.8d is not registered.
lines 2394-2424/2424 (END)

**Comment by vanelk** [comment]
@atkinsonchristian Do you have a microphone connected to your pi? If not you need one. You may also need to configure it. You can use arecord/aplay to test for the microphone or the alsamixer to test/adjust gains/levels.
